### ISSUE TITLE
No be able to Login

### ISSUE THREAD

**Issue by nit567esh** [shinyonfire/sof-auth-example#1]
Hi, I tried to use this and everything work fine except once clicked on login button nothing happen, ideally DataTable should appears as per you logic. Also use absolute path for each configs files but no luck..
Can you please suggest how i resolve this problem.

**Comment by merlinoa** [comment]
If you are running it locally you will need to sign up for Firebase and set up the firebase configuration as described in the README

**Comment by nit567esh** [comment]
Hi,
I’m doing the same as mentioned in readme. I can also see a user with my email if is registered in firebase user tab. Everything works fine but not be able to see datatable as output after login. After signing in action nothing is happening I’m still on the authorisation page.

**Comment by merlinoa** [comment]
I can't diagnose the problem without more information.  Have you checked the javascript console in your browser's developer tools for errors?

**Comment by nit567esh** [comment]
Now its working from my local laptop but when i'm trying to deploy it on shiny-server, showing 401 code.
is this due to firewall??
Uploaded image below,
![image](https://user-images.githubusercontent.com/11608306/50883472-2d159e80-140e-11e9-9e3a-47004f7812c4.png)

**Comment by merlinoa** [comment]
`Shiny.setInputValue()` was introduced in Shiny v1.1.  Are you using an older version of Shiny on your shiny-server?  If so you will need to use `Shiny.onInputChange()` instead.  Or you could upgrade Shiny on your Shiny server.

**Comment by nit567esh** [comment]
Worked :) Thanks for your help.
