### ISSUE TITLE
API key visible in the client

### ISSUE THREAD

**Issue by PaulC91** [shinyonfire/sof-auth-example#2]
Hi Andy,

Nice work on this! Looks like a promising auth option for shiny.

One thing I noticed was that the `apiKey`, `authDomain` and `projectId` are visible to anyone who looks at the `sof-auth.js` script in the source files of the app's base directory. 

I'm not a javascript expert but I'm guessing there must be a way of not exposing this information to the client?

**Comment by merlinoa** [comment]
Thanks Paul!  

Exposing these keys is not a problem with Firebase.  These keys are kept client side in all Firebase applications, and it is necessary to expose them for the Firebase project to work: https://stackoverflow.com/questions/37482366/is-it-safe-to-expose-firebase-apikey-to-the-public 
When you run the demo app, you can find these keys by poking around in your developer console.

Security in Firebase is determined by Firebase "rules".   I don't have any data in this demo, so I didn't bother to set up any rules.

**Comment by PaulC91** [comment]
Ah ok thanks for clearing that up!

On another note (sorry if changing the topic is bad github issue form) am I right in saying there's no way to set rules on who can verify themselves to your firebase app, so anyone who verifies their email can get through the auth stage?

I'm considering using this on a project over the [shinyauthr ](https://github.com/PaulC91/shinyauthr) package I built because I like the idea of not having to administer passwords and store them with the app - but I guess it would have to be a 2 stage process of letting anyone verify themselves but then stopping them getting through to any app content if their verified email doesn't match a list of emails stored in the app?

Would be interested to hear your thoughts and happy to take the conversation somewhere other than this issue if more appropriate! 

Thanks,
Paul

**Comment by merlinoa** [comment]
Oh nice!  I didn't put 2 and 2 together that you created `shinyauthr`.  `shinyauthr` is actually what inspired me to make this example app.  Thanks for creating that package!  Very cool!  

As for your question, there are many ways to limit access to firebase authentication.  You will need to modify `www/sof-auth.js` slightly.

Perhaps the most straightforward way is to create a vector in R of the email addresses of all users that should be able to register and sign up for your app.  Keep this vector in the Shiny app, and check the email address of the user attempting to register against this vector. You will need to use [Shiny's functions for communicating with javascript](https://shiny.rstudio.com/articles/communicating-with-js.html) to set this up.

You could also keep track of users that can register in [Firebase Firestore](https://firebase.google.com/docs/firestore/).  This is what I would do.

There are alternative solutions as well.  Please send me an email if you want to discuss further andy.merlino@tychobra.com.

Best,
Andy

**Comment by PaulC91** [comment]
Nice one, glad to hear it inspired `sof-auth`!

I'll have a play around with the `sof-auth.js` script and see what I can come up and fire you over an email next week if I get stuck, which I'm sure I will!

Cheers,
Paul
