### ISSUE TITLE
Question about security warning

### ISSUE THREAD

**Issue by jdwrink** [shinyonfire/sof-auth-example#7]
I saw you placed a security warning on the repo. Could you elaborate about the security risk? I assumed that as long as you use mTLS and use proper security rules with your Firebase project, then there shouldn’t be a security problem.

**Comment by merlinoa** [comment]
The signed in Shiny user is set via a Shiny input.  This is not secure because the front end user can  manually set Shiny input values in JavaScript with `Shiny.setInputValue()`.

**Comment by jdwrink** [comment]
How would one use this maliciously?
